# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 976c0acabb6c04a516ce1a82abe91a918bbf78080d9796e0aa63c2ab54afe22c3158d5c83845838a3a2ed22c693ccc64b348043dbe976789fe935173309b699a

test:
  secret_key_base: 93c0b359066903a283ec7be05b032712ea9fbc242708341e3a9070097a3164ebed170f51165e2023504c63bda626027b159d2fcea6c455bcba4150749ecc6196

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
